CREATE TABLE shops (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    date_updated TIMESTAMP DEFAULT now() NOT NULL,
    lat NUMERIC NOT NULL,
    long NUMERIC NOT NULL,
    telephone TEXT,
    statecode TEXT,
    address TEXT,
    url TEXT,
    zip TEXT,
    owned INTEGER DEFAULT 0,
    owner_id INTEGER
);

